name: Release

on:
  push:
    branches-ignore:
      - '*'
    tags:
      - '*.*.*' # push to versioned tag will trigger this build

env:
  DAZLAB_PAT: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - run: yarn install
      - run: yarn lint
      - run: npm publish --access=restricted
      - run: |
          gh release create "$GITHUB_REF_NAME" \
              --repo="$GITHUB_REPOSITORY" \
              --title="Release ${GITHUB_REF_NAME#v}" \
              --generate-notes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

